accounts:
  total: 0
client_credentials:
  address: http://localhost:4001
  apy_key: PdDVXJXE5wa9u8u8qcfec4ulMF0It0tt4sbxyTcw
  token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
